name: Netlify Document Staging Environment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publishMasterCommit:
    name: Deploying on Netlify Document Staging Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.action == 'closed' && github.pull_request.merged == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy docs
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DOCUMENT_ID }}
          deploy_alias: 'staging'
          build_directory: './docs